webtalk_init -webtalk_dir D:/Documents/EEL4783_VHDL/project/Neural_Network_Final_Project/Neural_Network_Final_Project.sim/sim_1/behav/xsim/xsim.dir/neuron_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Apr 11 16:09:23 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "319f68ce-0f08-4c0f-bfe9-338e920ed3f5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "824eec57844e4262a5930513da3fb005" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "45" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-9700KF CPU @ 3.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3600 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "10 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7528_KB" -context "xsim\\usage"
webtalk_transmit -clientid 558918675 -regid "" -xml D:/Documents/EEL4783_VHDL/project/Neural_Network_Final_Project/Neural_Network_Final_Project.sim/sim_1/behav/xsim/xsim.dir/neuron_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Documents/EEL4783_VHDL/project/Neural_Network_Final_Project/Neural_Network_Final_Project.sim/sim_1/behav/xsim/xsim.dir/neuron_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Documents/EEL4783_VHDL/project/Neural_Network_Final_Project/Neural_Network_Final_Project.sim/sim_1/behav/xsim/xsim.dir/neuron_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
